// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdqzxsqwblwrukhmlbqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcXp4c3F3Ymx3cnVraG1sYnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTU3NDMsImV4cCI6MjA3Mjk5MTc0M30.YyiRQDg5iN6fPi5uXkjq4FrCexyOHe-FyfBdBwyqIFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});